# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DesafioAppProva' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'AlamofireImage', '~> 3.2'
  pod 'PKHUD', '~> 4.2'
  # pod 'Quick', '~> 1.1'
  # pod 'Nimble', '~> 7.0'
  # Pods for DesafioAppProva

  target 'DesafioAppProvaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
